local EpsilonPhases = LibStub("AceAddon-3.0"):GetAddon("EpsilonPhases")
local addonName = ...
local addonPath = "Interface/AddOns/" .. tostring(addonName)

EpsilonPhases.ASSETS_PATH = addonPath .. "/assets"
EpsilonPhases.PHASELIST_ITEM_HEIGHT = 78
EpsilonPhases.PHASELIST_ITEM_COUNT = 7
EpsilonPhases.PHASEBACKGROUNDS_EMPTYSPACE_X = 144
EpsilonPhases.PHASEBACKGROUNDS_EMPTYSPACE_Y = 10
EpsilonPhases.PHASEBACKGROUNDS_X = 2048
EpsilonPhases.PHASEBACKGROUNDS_Y = 1024
EpsilonPhases.ICON_PATH = 'Interface/Icons/'
EpsilonPhases.SEND_ADDON_MESSAGE_PREFIX = "Phase_Codex"
EpsilonPhases.ADDON_COLOR = CreateColorFromHexString("FF2ECEFF"):GenerateHexColorMarkup()

EpsilonPhases.PHASE_BACKGROUNDS = {
"Stormwind",
"Orgrimmar",
"Elwynn Forest",
"Durotar",
"Ironforge",
"Thunderbluff",
"Bel'ameth",
"Undercity",
"Gnomeregan",
"Dun Morogh",
"Tirisfal Glade",
"Felwood",
"Loch Modan",
"Silverpine Forest",
"Westfall",
"Redridge",
"Duskwood",
"Hillsbrad Foothills",
"Wetlands",
"Alterac Valley",
"Arathi Highlands",
"Stranglethorn Vale",
"Badlands",
"Swamp of Sorrows",
"The Hinterlands",
"Searing Gorge",
"Blasted Lands",
"Burning Steppes",
"Plaguelands",
"Deadwind Pass",
"Thousand Needles",
"Darkshore",
"Azshara",
"Moonglade",
"The Echo Isles",
"Mulgore",
"Northern Barrens",
"Southern Barrens",
"Desolace",
"Stonetalon Mountains",
"Dustwallow Marsh",
"Tanaris",
"Silithus",
"Silithus Wound",
"Winterspring",
"Feralas",
"Un'goro Crater",
"Ghostlands",
"Bloodmyst Isle",
"Azuremyst Isle",
"Silvermoon",
"Exodar",
"Shattrath City",
"Terokkar Forest",
"Netherstorm",
"Blades Edge Mountains",
"Zangarmarsh",
"Hellfire Peninsula",
"Shadowmoon Valley",
"Isle of Quel'danas",
"Dalaran",
"Coldarra",
"Howling Fjord",
"Sholazar Basin",
"Grizzly Hills",
"Crystalsong Forest",
"Ulduar",
"Zul'Drak",
"Wintergrasp",
"Dragonblight",
"Storm Peaks",
"Vash'jir",
"Mount Hyjal",
"Gilneas",
"Kezan",
"Skywall",
"Deepholm",
"The Abyssal Maw",
"Firelands",
"Maelstrom",
"Twilight Highlands",
"Uldum Oasis",
"Uldum Desert",
"Wildhammer",
"Lost Isles",
"The Jade Forest",
"Valley of the Four Winds",
"Halfhill Farm",
"Dread Wastes",
"Kun Lai Summit",
"Vale of Eternal Blossoms",
"Townlong Steppes",
"Isle of Thunder",
"Shadowmoon Valley Draenor",
"Frostfire Ridge",
"Spires of Arak",
"Nagrand",
"Talador",
"Tanaan Jungle",
"Ashran",
"Gorgrond",
"Suramar City",
"Suramar Wilds",
"Highmountain",
"Stormheim",
"Val'sharah",
"Emerald Dreamway",
"Azeroth from Space",
"Krokuun",
"Eredath",
"Sanctum of Light",
"Chamber of the Guardian",
"Netherlight Temple",
"Dalaran Sewers",
"Halls of Valor",
"Wandering Isle",
"Acherus: The Ebon Hold",
"Dreadscar Rift",
"Fel Hammer",
"Trueshot Lodge",
"Telogrus Rift",
"The Heart of Azeroth",
"Invasion Point: Sangua",
"Invasion Point: Cen'gar",
"Invasion Point: Naigtal",
"Invasion Point: Bonich",
"Invasion Point: Aurinor",
"Invasion Point: Val",
"Elunaria",
"Rift of Aln",
"Drust Cave",
"Waycrest Manor",
"Freehold",
"Tiragarde Sound",
"Boralus",
"Vol'dun",
"Mechagon",
"Bwonsamdi's Temple",
"Nazmir",
"Zuldazar",
"Nazjatar",
"Nya'lotha",
"Temple of Sethraliss",
"Gates of Lordaeron",
"Stormsong Valley",
"Drustvar",
"Ardenweald",
"Maldraxxus",
"Revendreth",
"Bastion",
"Oribos",
"Torghast",
"Zereth Mortis",
"Tazavesh, the Veiled Market",
"Exile's Reach",
"Cosmic Guardian",
"Prophecy Lordaeron",
"Builder's Haven",
"Hallow's Edge",
"Dranosh Valley",
"Marbled",
"Circular",
"Arcane",
"Chaos",
"Life",
"Void",
"Light",
"Death",
}