local _, MogIt = ...

local L = MogIt.L

MogIt.enchants = {
	{
		{
			id = 2646,
			name = "Agility",
		},
		{
			id = 2564,
			name = "Agility",
		},
		{
			id = 1900,
			name = "Crusader",
		},
		{
			id = 912,
			name = "Demonslaying",
		},
		{
			id = 803,
			name = "Fiery Weapon",
		},
		{
			id = 963,
			name = "Greater Impact",
		},
		{
			id = 805,
			name = "Greater Striking",
		},
		{
			id = 2505,
			name = "Healing Power",
		},
		{
			id = 1894,
			name = "Icy Chill",
		},
		{
			id = 1897,
			name = "Impact",
		},
		{
			id = 853,
			name = "Lesser Beastslayer",
		},
		{
			id = 854,
			name = "Lesser Elemental Slayer",
		},
		{
			id = 943,
			name = "Lesser Impact",
		},
		{
			id = 723,
			name = "Lesser Intellect",
		},
		{
			id = 255,
			name = "Lesser Spirit",
		},
		{
			id = 241,
			name = "Lesser Striking",
		},
		{
			id = 1898,
			name = "Lifestealing",
		},
		{
			id = 1904,
			name = "Major Intellect",
		},
		{
			id = 1903,
			name = "Major Spirit",
		},
		{
			id = 2568,
			name = "Mighty Intellect",
		},
		{
			id = 2567,
			name = "Mighty Spirit",
		},
		{
			id = 249,
			name = "Minor Beastslayer",
		},
		{
			id = 4723,
			name = "Minor Impact",
		},
		{
			id = 250,
			name = "Minor Striking",
		},
		{
			id = 2504,
			name = "Spellpower",
		},
		{
			id = 2563,
			name = "Strength",
		},
		{
			id = 4745,
			name = "Striking",
		},
		{
			id = 1896,
			name = "Superior Impact",
		},
		{
			id = 1897,
			name = "Superior Striking",
		},
		{
			id = 1899,
			name = "Unholy Weapon",
		},
		{
			id = 2443,
			name = "Winter's Might",
		},
		name = L["Classic"],
	},
	{
		{
			id = 3788,
			name = "Accuracy",
		},
		{
			id = 4067,
			name = "Avalanche",
		},
		{
			id = 2675,
			name = "Battlemaster",
		},
		{
			id = 3789,
			name = "Berserking",
		},
		{
			id = 3790,
			name = "Black Magic",
		},
		{
			id = 3869,
			name = "Blade Ward",
		},
		{
			id = 3870,
			name = "Blood Draining",
		},
		{
			id = 5125,
			name = "Bloody Dancing Steel",
		},
		{
			id = 4445,
			name = "Colossus",
		},
		{
			id = 4444,
			name = "Dancing Steel",
		},
		{
			id = 3273,
			name = "Deathfrost",
		},
		{
			id = 4443,
			name = "Elemental Force",
		},
		{
			id = 4074,
			name = "Elemental Slayer",
		},
		{
			id = 1103,
			name = "Exceptional Agility",
		},
		{
			id = 3830,
			name = "Exceptional Spellpower",
		},
		{
			id = 3844,
			name = "Exceptional Spirit",
		},
		{
			id = 3225,
			name = "Executioner",
		},
		{
			id = 3251,
			name = "Giantslaying",
		},
		{
			id = 5035,
			name = "Glorious Tyranny",
		},
		{
			id = 3222,
			name = "Greater Agility",
		},
		{
			id = 1606,
			name = "Greater Potency",
		},
		{
			id = 3828,
			name = "Greater Savagery",
		},
		{
			id = 3854,
			name = "Greater Spellpower",
		},
		{
			id = 4084,
			name = "Heartsong",
		},
		{
			id = 4083,
			name = "Hurricane",
		},
		{
			id = 3239,
			name = "Icebreaker Weapon",
		},
		{
			id = 4442,
			name = "Jade Spirit",
		},
		{
			id = 4099,
			name = "Landslide",
		},
		{
			id = 3241,
			name = "Lifeward",
		},
		{
			id = 2670,
			name = "Major Agility",
		},
		{
			id = 3846,
			name = "Major Healing",
		},
		{
			id = 2666,
			name = "Major Intellect",
		},
		{
			id = 2669,
			name = "Major Spellpower",
		},
		{
			id = 4746,
			name = "Major Striking",
		},
		{
			id = 5336,
			name = "Mark of Blackrock",
		},
		{
			id = 5384,
			name = "Mark of Bleeding Hollow",
		},
		{
			id = 5335,
			name = "Mark of Shadowmoon",
		},
		{
			id = 5334,
			name = "Mark of the Frostwolf",
		},
		{
			id = 5331,
			name = "Mark of the Shattered Hand",
		},
		{
			id = 5330,
			name = "Mark of the Thunderlord",
		},
		{
			id = 5337,
			name = "Mark of Warsong",
		},
		{
			id = 3827,
			name = "Massacre",
		},
		{
			id = 4066,
			name = "Mending",
		},
		{
			id = 4227,
			name = "Mighty Agility",
		},
		{
			id = 3834,
			name = "Mighty Spellpower",
		},
		{
			id = 2673,
			name = "Mongoose",
		},
		{
			id = 2668,
			name = "Potency",
		},
		{
			id = 4097,
			name = "Power Torrent",
		},
		{
			id = 4446,
			name = "River's Song",
		},
		{
			id = 2667,
			name = "Savagery",
		},
		{
			id = 3247,
			name = "Scourgebane",
		},
		{
			id = 2672,
			name = "Soulfrost",
		},
		{
			id = 3855,
			name = "Spellpower",
		},
		{
			id = 2674,
			name = "Spellsurge",
		},
		{
			id = 5124,
			name = "Spirit of Conquest",
		},
		{
			id = 2671,
			name = "Sunfire",
		},
		{
			id = 3833,
			name = "Superior Potency",
		},
		{
			id = 4441,
			name = "Windsong",
		},
		{
			id = 4098,
			name = "Windwalk",
		},
		name = L["Expansions"],
	},
	{
		{
			id = 5946,
			name = "Coastal Surge"
		},
		{
			id = 6148,
			name = "Force Multiplier"
		},
		{
			id = 5950,
			name = "Gale-Force Striking"
		},
		{
			id = 6112,
			name = "Machinist's Brilliance"
		},
		{
			id = 5964,
			name = "Masterful Navigation"
		},
		{
			id = 6150,
			name = "Naga Hide"
		},
		{
			id = 6149,
			name = "Oceanic Restoration"
		},
		{
			id = 5963,
			name = "Quick Navigation"
		},
		{
			id = 5948,
			name = "Siphoning"
		},
		{
			id = 5966,
			name = "Stalwart Navigation"
		},
		{
			id = 5949,
			name = "Torrent of Elements"
		},
		{
			id = 5962,
			name = "Versatile Navigation"
		},
		name = L["Battle for Azeroth"],
	},
	{
		{
			id = 6227,
			name = "Ascended Vigor"
		},
		{
			id = 6229,
			name = "Celestial Guidance"
		},
		{
			id = 6226,
			name = "Eternal Grace"
		},
		{
			id = 6223,
			name = "Lightless Force"
		},
		{
			id = 6228,
			name = "Sinful Revelation"
		},
		name = L["Shadowlands"],
	},
	{
		{
			id = 3369,
			name = "Rune of Cinderglacier",
		},
		{
			id = 3366,
			name = "Rune of Lichbane",
		},
		{
			id = 3370,
			name = "Rune of Razorice",
		},
		{
			id = 3595,
			name = "Rune of Spellbreaking",
		},
		{
			id = 3367,
			name = "Rune of Spellshattering",
		},
		{
			id = 3594,
			name = "Rune of Swordbreaking",
		},
		{
			id = 3365,
			name = "Rune of Swordshattering",
		},
		{
			id = 3368,
			name = "Rune of the Fallen Crusader",
		},
		{
			id = 3883,
			name = "Rune of the Nerubian Carapace",
		},
		{
			id = 3847,
			name = "Rune of the Stoneskin Gargoyle",
		},
		name = L["Runeforging"],
	},
	{
		{ id = 9001, name = "Epsilon Enchantment" },
		{ id = 9002, name = "Epsilon Enchantment" },
		{ id = 9024, name = "Epsilon Enchantment" },
		{ id = 9025, name = "Epsilon Enchantment" },
		{ id = 9026, name = "Epsilon Enchantment" },
		{ id = 9027, name = "Epsilon Enchantment" },
		{ id = 9028, name = "Epsilon Enchantment" },
		{ id = 9029, name = "Epsilon Enchantment" },
		{ id = 9030, name = "Epsilon Enchantment" },
		{ id = 9031, name = "Epsilon Enchantment" },
		{ id = 9032, name = "Epsilon Enchantment" },
		{ id = 9033, name = "Epsilon Enchantment" },
		{ id = 9042, name = "Epsilon Enchantment" },
		{ id = 9061, name = "Epsilon Enchantment" },
		{ id = 9081, name = "Epsilon Enchantment" },
		{ id = 9101, name = "Epsilon Enchantment" },
		{ id = 9102, name = "Epsilon Enchantment" },
		{ id = 9103, name = "Epsilon Enchantment" },
		{ id = 9104, name = "Epsilon Enchantment" },
		{ id = 9105, name = "Epsilon Enchantment" },
		{ id = 9106, name = "Epsilon Enchantment" },
		{ id = 9107, name = "Epsilon Enchantment" },
		{ id = 9123, name = "Epsilon Enchantment" },
		{ id = 9124, name = "Epsilon Enchantment" },
		{ id = 9125, name = "Epsilon Enchantment" },
		{ id = 9126, name = "Epsilon Enchantment" },
		{ id = 9127, name = "Epsilon Enchantment" },
		{ id = 9128, name = "Epsilon Enchantment" },
		{ id = 9129, name = "Epsilon Enchantment" },
		{ id = 9130, name = "Epsilon Enchantment" },
		{ id = 9131, name = "Epsilon Enchantment" },
		{ id = 9132, name = "Epsilon Enchantment" },
		{ id = 9133, name = "Epsilon Enchantment" },
		{ id = 9134, name = "Epsilon Enchantment" },
		{ id = 9135, name = "Epsilon Enchantment" },
		{ id = 9137, name = "Epsilon Enchantment" },
		{ id = 9138, name = "Epsilon Enchantment" },
		{ id = 9139, name = "Epsilon Enchantment" },
		{ id = 9140, name = "Epsilon Enchantment" },
		{ id = 9141, name = "Epsilon Enchantment" },
		{ id = 9142, name = "Epsilon Enchantment" },
		{ id = 9143, name = "Epsilon Enchantment" },
		{ id = 9144, name = "Epsilon Enchantment" },
		{ id = 9145, name = "Epsilon Enchantment" },
		{ id = 9146, name = "Epsilon Enchantment" },
		{ id = 9147, name = "Epsilon Enchantment" },
		{ id = 9148, name = "Epsilon Enchantment" },
		{ id = 9149, name = "Epsilon Enchantment" },
		{ id = 9150, name = "Epsilon Enchantment" },
		{ id = 9151, name = "Epsilon Enchantment" },
		{ id = 9152, name = "Epsilon Enchantment" },
		{ id = 9153, name = "Epsilon Enchantment" },
		{ id = 9154, name = "Epsilon Enchantment" },
		{ id = 9155, name = "Epsilon Enchantment" },
		{ id = 9156, name = "Epsilon Enchantment" },
		{ id = 9157, name = "Epsilon Enchantment" },
		{ id = 9158, name = "Epsilon Enchantment" },
		{ id = 9159, name = "Epsilon Enchantment" },
		{ id = 9160, name = "Epsilon Enchantment" },
		{ id = 9161, name = "Epsilon Enchantment" },
		{ id = 9162, name = "Epsilon Enchantment" },
		{ id = 9164, name = "Epsilon Enchantment" },
		{ id = 9165, name = "Epsilon Enchantment" },
		{ id = 9166, name = "Epsilon Enchantment" },
		{ id = 9167, name = "Epsilon Enchantment" },
		{ id = 9168, name = "Epsilon Enchantment" },
		{ id = 9169, name = "Epsilon Enchantment" },
		{ id = 9170, name = "Epsilon Enchantment" },
		{ id = 9171, name = "Epsilon Enchantment" },
		{ id = 9172, name = "Epsilon Enchantment" },
		{ id = 9173, name = "Epsilon Enchantment" },
		{ id = 9174, name = "Epsilon Enchantment" },
		{ id = 9175, name = "Epsilon Enchantment" },
		{ id = 9176, name = "Epsilon Enchantment" },
		{ id = 9178, name = "Epsilon Enchantment" },
		{ id = 9179, name = "Epsilon Enchantment" },
		{ id = 9180, name = "Epsilon Enchantment" },
		{ id = 9181, name = "Epsilon Enchantment" },
		{ id = 9183, name = "Epsilon Enchantment" },
		{ id = 9184, name = "Epsilon Enchantment" },
		{ id = 9185, name = "Epsilon Enchantment" },
		{ id = 9186, name = "Epsilon Enchantment" },
		{ id = 9187, name = "Epsilon Enchantment" },
		{ id = 9188, name = "Epsilon Enchantment" },
		{ id = 9189, name = "Epsilon Enchantment" },
		{ id = 9191, name = "Epsilon Enchantment" },
		{ id = 9192, name = "Epsilon Enchantment" },
		{ id = 9193, name = "Epsilon Enchantment" },
		{ id = 9194, name = "Epsilon Enchantment" },
		{ id = 9195, name = "Epsilon Enchantment" },
		{ id = 9196, name = "Epsilon Enchantment" },
		{ id = 9197, name = "Epsilon Enchantment" },
		{ id = 9198, name = "Epsilon Enchantment" },
		{ id = 9199, name = "Epsilon Enchantment" },
		{ id = 9200, name = "Epsilon Enchantment" },
		{ id = 9201, name = "Epsilon Enchantment" },
		{ id = 9213, name = "Epsilon Enchantment" },
		{ id = 9219, name = "Epsilon Enchantment" },
		{ id = 9220, name = "Epsilon Enchantment" },
		{ id = 9221, name = "Epsilon Enchantment" },
		{ id = 9222, name = "Epsilon Enchantment" },
		name = L["Epsilon (9001-9222)"],
	},
	{
		{ id = 9229, name = "Epsilon Enchantment" },
		{ id = 9235, name = "Epsilon Enchantment" },
		{ id = 9236, name = "Epsilon Enchantment" },
		{ id = 9237, name = "Epsilon Enchantment" },
		{ id = 9238, name = "Epsilon Enchantment" },
		{ id = 9239, name = "Epsilon Enchantment" },
		{ id = 9242, name = "Epsilon Enchantment" },
		{ id = 9243, name = "Epsilon Enchantment" },
		{ id = 9244, name = "Epsilon Enchantment" },
		{ id = 9245, name = "Epsilon Enchantment" },
		{ id = 9246, name = "Epsilon Enchantment" },
		{ id = 9247, name = "Epsilon Enchantment" },
		{ id = 9248, name = "Epsilon Enchantment" },
		{ id = 9249, name = "Epsilon Enchantment" },
		{ id = 9250, name = "Epsilon Enchantment" },
		{ id = 9251, name = "Epsilon Enchantment" },
		{ id = 9252, name = "Epsilon Enchantment" },
		{ id = 9253, name = "Epsilon Enchantment" },
		{ id = 9254, name = "Epsilon Enchantment" },
		{ id = 9255, name = "Epsilon Enchantment" },
		{ id = 9257, name = "Epsilon Enchantment" },
		{ id = 9258, name = "Epsilon Enchantment" },
		{ id = 9259, name = "Epsilon Enchantment" },
		{ id = 9260, name = "Epsilon Enchantment" },
		{ id = 9263, name = "Epsilon Enchantment" },
		{ id = 9264, name = "Epsilon Enchantment" },
		{ id = 9265, name = "Epsilon Enchantment" },
		{ id = 9266, name = "Epsilon Enchantment" },
		{ id = 9267, name = "Epsilon Enchantment" },
		{ id = 9270, name = "Epsilon Enchantment" },
		{ id = 9271, name = "Epsilon Enchantment" },
		{ id = 9272, name = "Epsilon Enchantment" },
		{ id = 9273, name = "Epsilon Enchantment" },
		{ id = 9274, name = "Epsilon Enchantment" },
		{ id = 9275, name = "Epsilon Enchantment" },
		{ id = 9276, name = "Epsilon Enchantment" },
		{ id = 9280, name = "Epsilon Enchantment" },
		{ id = 9281, name = "Epsilon Enchantment" },
		{ id = 9282, name = "Epsilon Enchantment" },
		{ id = 9283, name = "Epsilon Enchantment" },
		{ id = 9284, name = "Epsilon Enchantment" },
		{ id = 9285, name = "Epsilon Enchantment" },
		{ id = 9286, name = "Epsilon Enchantment" },
		{ id = 9287, name = "Epsilon Enchantment" },
		{ id = 9290, name = "Epsilon Enchantment" },
		{ id = 9291, name = "Epsilon Enchantment" },
		{ id = 9292, name = "Epsilon Enchantment" },
		{ id = 9293, name = "Epsilon Enchantment" },
		{ id = 9294, name = "Epsilon Enchantment" },
		{ id = 9295, name = "Epsilon Enchantment" },
		{ id = 9296, name = "Epsilon Enchantment" },
		{ id = 9297, name = "Epsilon Enchantment" },
		{ id = 9298, name = "Epsilon Enchantment" },
		{ id = 9299, name = "Epsilon Enchantment" },
		{ id = 9300, name = "Epsilon Enchantment" },
		{ id = 9301, name = "Epsilon Enchantment" },
		{ id = 9302, name = "Epsilon Enchantment" },
		{ id = 9303, name = "Epsilon Enchantment" },
		{ id = 9304, name = "Epsilon Enchantment" },
		{ id = 9305, name = "Epsilon Enchantment" },
		{ id = 9306, name = "Epsilon Enchantment" },
		{ id = 9307, name = "Epsilon Enchantment" },
		{ id = 9308, name = "Epsilon Enchantment" },
		{ id = 9309, name = "Epsilon Enchantment" },
		{ id = 9310, name = "Epsilon Enchantment" },
		{ id = 9311, name = "Epsilon Enchantment" },
		{ id = 9312, name = "Epsilon Enchantment" },
		{ id = 9313, name = "Epsilon Enchantment" },
		{ id = 9314, name = "Epsilon Enchantment" },
		{ id = 9315, name = "Epsilon Enchantment" },
		{ id = 9316, name = "Epsilon Enchantment" },
		{ id = 9317, name = "Epsilon Enchantment" },
		{ id = 9320, name = "Epsilon Enchantment" },
		{ id = 9321, name = "Epsilon Enchantment" },
		{ id = 9322, name = "Epsilon Enchantment" },
		{ id = 9323, name = "Epsilon Enchantment" },
		{ id = 9324, name = "Epsilon Enchantment" },
		{ id = 9325, name = "Epsilon Enchantment" },
		{ id = 9327, name = "Epsilon Enchantment" },
		{ id = 9328, name = "Epsilon Enchantment" },
		{ id = 9329, name = "Epsilon Enchantment" },
		{ id = 9330, name = "Epsilon Enchantment" },
		{ id = 9332, name = "Epsilon Enchantment" },
		{ id = 9333, name = "Epsilon Enchantment" },
		{ id = 9334, name = "Epsilon Enchantment" },
		{ id = 9335, name = "Epsilon Enchantment" },
		{ id = 9336, name = "Epsilon Enchantment" },
		{ id = 9337, name = "Epsilon Enchantment" },
		{ id = 9338, name = "Epsilon Enchantment" },
		{ id = 9339, name = "Epsilon Enchantment" },
		{ id = 9340, name = "Epsilon Enchantment" },
		{ id = 9341, name = "Epsilon Enchantment" },
		{ id = 9342, name = "Epsilon Enchantment" },
		{ id = 9343, name = "Epsilon Enchantment" },
		{ id = 9344, name = "Epsilon Enchantment" },
		{ id = 9345, name = "Epsilon Enchantment" },
		{ id = 9346, name = "Epsilon Enchantment" },
		{ id = 9347, name = "Epsilon Enchantment" },
		{ id = 9348, name = "Epsilon Enchantment" },
		{ id = 9352, name = "Epsilon Enchantment" },
		{ id = 9453, name = "Epsilon Enchantment" },
		name = L["Epsilon (9229-9453)"],
	},
	{
		{ id = 9454, name = "Epsilon Enchantment" },
		{ id = 9456, name = "Epsilon Enchantment" },
		{ id = 9464, name = "Epsilon Enchantment" },
		{ id = 9465, name = "Epsilon Enchantment" },
		{ id = 9466, name = "Epsilon Enchantment" },
		{ id = 9467, name = "Epsilon Enchantment" },
		{ id = 9468, name = "Epsilon Enchantment" },
		{ id = 9469, name = "Epsilon Enchantment" },
		{ id = 9470, name = "Epsilon Enchantment" },
		{ id = 9471, name = "Epsilon Enchantment" },
		{ id = 9472, name = "Epsilon Enchantment" },
		{ id = 9473, name = "Epsilon Enchantment" },
		{ id = 9474, name = "Epsilon Enchantment" },
		{ id = 9475, name = "Epsilon Enchantment" },
		{ id = 9476, name = "Epsilon Enchantment" },
		{ id = 9477, name = "Epsilon Enchantment" },
		{ id = 9478, name = "Epsilon Enchantment" },
		{ id = 9479, name = "Epsilon Enchantment" },
		{ id = 9480, name = "Epsilon Enchantment" },
		{ id = 9483, name = "Epsilon Enchantment" },
		{ id = 9484, name = "Epsilon Enchantment" },
		{ id = 9485, name = "Epsilon Enchantment" },
		{ id = 9486, name = "Epsilon Enchantment" },
		{ id = 9487, name = "Epsilon Enchantment" },
		{ id = 9489, name = "Epsilon Enchantment" },
		{ id = 9490, name = "Epsilon Enchantment" },
		{ id = 9491, name = "Epsilon Enchantment" },
		{ id = 9492, name = "Epsilon Enchantment" },
		{ id = 9493, name = "Epsilon Enchantment" },
		{ id = 9494, name = "Epsilon Enchantment" },
		{ id = 9495, name = "Epsilon Enchantment" },
		{ id = 9496, name = "Epsilon Enchantment" },
		{ id = 9497, name = "Epsilon Enchantment" },
		{ id = 9498, name = "Epsilon Enchantment" },
		{ id = 9499, name = "Epsilon Enchantment" },
		{ id = 9500, name = "Epsilon Enchantment" },
		{ id = 9501, name = "Epsilon Enchantment" },
		{ id = 9502, name = "Epsilon Enchantment" },
		{ id = 9503, name = "Epsilon Enchantment" },
		{ id = 9504, name = "Epsilon Enchantment" },
		{ id = 9505, name = "Epsilon Enchantment" },
		{ id = 9506, name = "Epsilon Enchantment" },
		{ id = 9507, name = "Epsilon Enchantment" },
		{ id = 9508, name = "Epsilon Enchantment" },
		{ id = 9511, name = "Epsilon Enchantment" },
		{ id = 9512, name = "Epsilon Enchantment" },
		{ id = 9513, name = "Epsilon Enchantment" },
		{ id = 9514, name = "Epsilon Enchantment" },
		{ id = 9515, name = "Epsilon Enchantment" },
		{ id = 9516, name = "Epsilon Enchantment" },
		{ id = 9517, name = "Epsilon Enchantment" },
		{ id = 9518, name = "Epsilon Enchantment" },
		{ id = 9519, name = "Epsilon Enchantment" },
		{ id = 9520, name = "Epsilon Enchantment" },
		{ id = 9521, name = "Epsilon Enchantment" },
		{ id = 9522, name = "Epsilon Enchantment" },
		{ id = 9523, name = "Epsilon Enchantment" },
		{ id = 9524, name = "Epsilon Enchantment" },
		{ id = 9525, name = "Epsilon Enchantment" },
		{ id = 9526, name = "Epsilon Enchantment" },
		{ id = 9527, name = "Epsilon Enchantment" },
		{ id = 9528, name = "Epsilon Enchantment" },
		{ id = 9529, name = "Epsilon Enchantment" },
		{ id = 9530, name = "Epsilon Enchantment" },
		{ id = 9531, name = "Epsilon Enchantment" },
		{ id = 9532, name = "Epsilon Enchantment" },
		{ id = 9533, name = "Epsilon Enchantment" },
		{ id = 9534, name = "Epsilon Enchantment" },
		{ id = 9535, name = "Epsilon Enchantment" },
		{ id = 9536, name = "Epsilon Enchantment" },
		{ id = 9537, name = "Epsilon Enchantment" },
		{ id = 9538, name = "Epsilon Enchantment" },
		{ id = 9539, name = "Epsilon Enchantment" },
		{ id = 9540, name = "Epsilon Enchantment" },
		{ id = 9541, name = "Epsilon Enchantment" },
		{ id = 9542, name = "Epsilon Enchantment" },
		{ id = 9543, name = "Epsilon Enchantment" },
		{ id = 9544, name = "Epsilon Enchantment" },
		{ id = 9545, name = "Epsilon Enchantment" },
		{ id = 9546, name = "Epsilon Enchantment" },
		{ id = 9547, name = "Epsilon Enchantment" },
		{ id = 9548, name = "Epsilon Enchantment" },
		{ id = 9549, name = "Epsilon Enchantment" },
		{ id = 9550, name = "Epsilon Enchantment" },
		{ id = 9551, name = "Epsilon Enchantment" },
		{ id = 9552, name = "Epsilon Enchantment" },
		{ id = 9553, name = "Epsilon Enchantment" },
		{ id = 9554, name = "Epsilon Enchantment" },
		{ id = 9555, name = "Epsilon Enchantment" },
		{ id = 9556, name = "Epsilon Enchantment" },
		{ id = 9557, name = "Epsilon Enchantment" },
		{ id = 9558, name = "Epsilon Enchantment" },
		{ id = 9559, name = "Epsilon Enchantment" },
		{ id = 9560, name = "Epsilon Enchantment" },
		{ id = 9561, name = "Epsilon Enchantment" },
		{ id = 9562, name = "Epsilon Enchantment" },
		{ id = 9563, name = "Epsilon Enchantment" },
		{ id = 9564, name = "Epsilon Enchantment" },
		{ id = 9565, name = "Epsilon Enchantment" },
		{ id = 9566, name = "Epsilon Enchantment" },
		{ id = 9567, name = "Epsilon Enchantment" },
		name = L["Epsilon (9454-9567)"],
	},
	{
		{ id = 9568, name = "Epsilon Enchantment" },
		{ id = 9569, name = "Epsilon Enchantment" },
		{ id = 9570, name = "Epsilon Enchantment" },
		{ id = 9571, name = "Epsilon Enchantment" },
		{ id = 9572, name = "Epsilon Enchantment" },
		{ id = 9573, name = "Epsilon Enchantment" },
		{ id = 9574, name = "Epsilon Enchantment" },
		{ id = 9575, name = "Epsilon Enchantment" },
		{ id = 9576, name = "Epsilon Enchantment" },
		{ id = 9577, name = "Epsilon Enchantment" },
		{ id = 9578, name = "Epsilon Enchantment" },
		{ id = 9579, name = "Epsilon Enchantment" },
		{ id = 9580, name = "Epsilon Enchantment" },
		{ id = 9581, name = "Epsilon Enchantment" },
		{ id = 9582, name = "Epsilon Enchantment" },
		{ id = 9583, name = "Epsilon Enchantment" },
		{ id = 9584, name = "Epsilon Enchantment" },
		{ id = 9585, name = "Epsilon Enchantment" },
		{ id = 9586, name = "Epsilon Enchantment" },
		{ id = 9587, name = "Epsilon Enchantment" },
		{ id = 9588, name = "Epsilon Enchantment" },
		{ id = 9589, name = "Epsilon Enchantment" },
		{ id = 9590, name = "Epsilon Enchantment" },
		{ id = 9591, name = "Epsilon Enchantment" },
		{ id = 9592, name = "Epsilon Enchantment" },
		{ id = 9593, name = "Epsilon Enchantment" },
		{ id = 9594, name = "Epsilon Enchantment" },
		{ id = 9595, name = "Epsilon Enchantment" },
		{ id = 9596, name = "Epsilon Enchantment" },
		{ id = 9597, name = "Epsilon Enchantment" },
		{ id = 9598, name = "Epsilon Enchantment" },
		{ id = 9599, name = "Epsilon Enchantment" },
		{ id = 9600, name = "Epsilon Enchantment" },
		{ id = 9601, name = "Epsilon Enchantment" },
		{ id = 9602, name = "Epsilon Enchantment" },
		{ id = 9603, name = "Epsilon Enchantment" },
		{ id = 9604, name = "Epsilon Enchantment" },
		{ id = 9605, name = "Epsilon Enchantment" },
		{ id = 9606, name = "Epsilon Enchantment" },
		{ id = 9607, name = "Epsilon Enchantment" },
		{ id = 9608, name = "Epsilon Enchantment" },
		{ id = 9609, name = "Epsilon Enchantment" },
		{ id = 9610, name = "Epsilon Enchantment" },
		{ id = 9611, name = "Epsilon Enchantment" },
		{ id = 9612, name = "Epsilon Enchantment" },
		{ id = 9613, name = "Epsilon Enchantment" },
		{ id = 9614, name = "Epsilon Enchantment" },
		{ id = 9615, name = "Epsilon Enchantment" },
		{ id = 9616, name = "Epsilon Enchantment" },
		{ id = 9617, name = "Epsilon Enchantment" },
		{ id = 9618, name = "Epsilon Enchantment" },
		{ id = 9619, name = "Epsilon Enchantment" },
		{ id = 9620, name = "Epsilon Enchantment" },
		{ id = 9621, name = "Epsilon Enchantment" },
		{ id = 9622, name = "Epsilon Enchantment" },
		name = L["Epsilon (9568-9622)"],
	},
	--[=[
	{
		name = L["Illusions"],
	},
	--]=]
};
