---@class ns
local ns = select(2, ...)

local LibRPMedia = ns.Libs.LibRPMedia

local Gems = ns.UI.Gems
local dprint = ns.Logging.dprint
local ASSETS_PATH = ns.Constants.ASSETS_PATH
local ICON_PATH = ASSETS_PATH .. "/icons/"

local function getIconSubPath(...)
	local paths = { ... }
	return ICON_PATH .. table.concat(paths, "/")
end

local FALLBACK_ICON = "Interface/Icons/inv_misc_questionmark"

local iconList = {};

-- Generate the default icon list using LibRPMedia.


local numLibIcons -- this will end as the number of icons in the Library database. Anything over that is custom. We don't currently use this however..

for index, name in LibRPMedia:FindAllIcons() do
	numLibIcons = #iconList
	iconList[numLibIcons + 1] = name;
end

-- Insert the custom icons.

local SCFORGE_CUSTOM_ICONS = { -- manually defined because it needs to be stable. Do not add things in the middle, only add to the end! And don't delete either!
	Gems.gemPath("Red"),
	Gems.gemPath("Orange"),
	Gems.gemPath("Yellow"),
	Gems.gemPath("Jade"),
	Gems.gemPath("Green"),
	Gems.gemPath("Blue"),
	Gems.gemPath("Violet"),
	Gems.gemPath("Indigo"),
	Gems.gemPath("Pink"),
	Gems.gemPath("Prismatic"),
	getIconSubPath("Arcanum_ArcFox"),
	getIconSubPath("Arcanum_ArmourRed"),
	getIconSubPath("Arcanum_ArmourOrange"),
	getIconSubPath("Arcanum_ArmourYellow"),
	getIconSubPath("Arcanum_ArmourJade"),
	getIconSubPath("Arcanum_ArmourGreen"),
	getIconSubPath("Arcanum_ArmourBlue"),
	getIconSubPath("Arcanum_ArmourViolet"),
	getIconSubPath("Arcanum_ArmourIndigo"),
	getIconSubPath("Arcanum_ArmourPink"),
	getIconSubPath("Arcanum_ArmourPrismatic"),
	getIconSubPath("Arcanum_BarrageRed"),
	getIconSubPath("Arcanum_BarrageOrange"),
	getIconSubPath("Arcanum_BarrageYellow"),
	getIconSubPath("Arcanum_BarrageJade"),
	getIconSubPath("Arcanum_BarrageGreen"),
	getIconSubPath("Arcanum_BarrageBlue"),
	getIconSubPath("Arcanum_BarrageViolet"),
	getIconSubPath("Arcanum_BarrageIndigo"),
	getIconSubPath("Arcanum_BarragePink"),
	getIconSubPath("Arcanum_BarragePrismatic"),
	getIconSubPath("Arcanum_BarrierRed"),
	getIconSubPath("Arcanum_BarrierOrange"),
	getIconSubPath("Arcanum_BarrierYellow"),
	getIconSubPath("Arcanum_BarrierJade"),
	getIconSubPath("Arcanum_BarrierGreen"),
	getIconSubPath("Arcanum_BarrierBlue"),
	getIconSubPath("Arcanum_BarrierViolet"),
	getIconSubPath("Arcanum_BarrierIndigo"),
	getIconSubPath("Arcanum_BarrierPink"),
	getIconSubPath("Arcanum_BarrierPrismatic"),
	getIconSubPath("Arcanum_BladeRed"),
	getIconSubPath("Arcanum_BladeOrange"),
	getIconSubPath("Arcanum_BladeYellow"),
	getIconSubPath("Arcanum_BladeJade"),
	getIconSubPath("Arcanum_BladeGreen"),
	getIconSubPath("Arcanum_BladeBlue"),
	getIconSubPath("Arcanum_BladeViolet"),
	getIconSubPath("Arcanum_BladeIndigo"),
	getIconSubPath("Arcanum_BladePink"),
	getIconSubPath("Arcanum_BladePrismatic"),
	getIconSubPath("Arcanum_BookRed"),
	getIconSubPath("Arcanum_BookOrange"),
	getIconSubPath("Arcanum_BookYellow"),
	getIconSubPath("Arcanum_BookJade"),
	getIconSubPath("Arcanum_BookGreen"),
	getIconSubPath("Arcanum_BookBlue"),
	getIconSubPath("Arcanum_BookViolet"),
	getIconSubPath("Arcanum_BookIndigo"),
	getIconSubPath("Arcanum_BookPink"),
	getIconSubPath("Arcanum_BookPrismatic"),
	getIconSubPath("Arcanum_FistRed"),
	getIconSubPath("Arcanum_FistOrange"),
	getIconSubPath("Arcanum_FistYellow"),
	getIconSubPath("Arcanum_FistJade"),
	getIconSubPath("Arcanum_FistGreen"),
	getIconSubPath("Arcanum_FistBlue"),
	getIconSubPath("Arcanum_FistViolet"),
	getIconSubPath("Arcanum_FistIndigo"),
	getIconSubPath("Arcanum_FistPink"),
	getIconSubPath("Arcanum_FistPrismatic"),
	getIconSubPath("Arcanum_GemRed"),
	getIconSubPath("Arcanum_GemOrange"),
	getIconSubPath("Arcanum_GemYellow"),
	getIconSubPath("Arcanum_GemJade"),
	getIconSubPath("Arcanum_GemGreen"),
	getIconSubPath("Arcanum_GemBlue"),
	getIconSubPath("Arcanum_GemViolet"),
	getIconSubPath("Arcanum_GemIndigo"),
	getIconSubPath("Arcanum_GemPink"),
	getIconSubPath("Arcanum_GemPrismatic"),
	getIconSubPath("Arcanum_MiasmaRed"),
	getIconSubPath("Arcanum_MiasmaOrange"),
	getIconSubPath("Arcanum_MiasmaYellow"),
	getIconSubPath("Arcanum_MiasmaJade"),
	getIconSubPath("Arcanum_MiasmaGreen"),
	getIconSubPath("Arcanum_MiasmaBlue"),
	getIconSubPath("Arcanum_MiasmaViolet"),
	getIconSubPath("Arcanum_MiasmaIndigo"),
	getIconSubPath("Arcanum_MiasmaPink"),
	getIconSubPath("Arcanum_MiasmaPrismatic"),
	getIconSubPath("Arcanum_OrbRed"),
	getIconSubPath("Arcanum_OrbOrange"),
	getIconSubPath("Arcanum_OrbYellow"),
	getIconSubPath("Arcanum_OrbJade"),
	getIconSubPath("Arcanum_OrbGreen"),
	getIconSubPath("Arcanum_OrbBlue"),
	getIconSubPath("Arcanum_OrbViolet"),
	getIconSubPath("Arcanum_OrbIndigo"),
	getIconSubPath("Arcanum_OrbPink"),
	getIconSubPath("Arcanum_OrbPrismatic"),
	getIconSubPath("Arcanum_ShowerRed"),
	getIconSubPath("Arcanum_ShowerOrange"),
	getIconSubPath("Arcanum_ShowerYellow"),
	getIconSubPath("Arcanum_ShowerJade"),
	getIconSubPath("Arcanum_ShowerGreen"),
	getIconSubPath("Arcanum_ShowerBlue"),
	getIconSubPath("Arcanum_ShowerViolet"),
	getIconSubPath("Arcanum_ShowerIndigo"),
	getIconSubPath("Arcanum_ShowerPink"),
	getIconSubPath("Arcanum_ShowerPrismatic"),
	getIconSubPath("Arcanum_SprintRed"),
	getIconSubPath("Arcanum_SprintOrange"),
	getIconSubPath("Arcanum_SprintYellow"),
	getIconSubPath("Arcanum_SprintJade"),
	getIconSubPath("Arcanum_SprintGreen"),
	getIconSubPath("Arcanum_SprintBlue"),
	getIconSubPath("Arcanum_SprintViolet"),
	getIconSubPath("Arcanum_SprintIndigo"),
	getIconSubPath("Arcanum_SprintPink"),
	getIconSubPath("Arcanum_SprintPrismatic"),
	getIconSubPath("Arcanum_XtraApertus"),
	getIconSubPath("Arcanum_XtraArcanowl"),
	getIconSubPath("Arcanum_XtraArcTea"),
	getIconSubPath("Arcanum_XtraArcWolf"),
	getIconSubPath("Arcanum_XtraArrowDown"),
	getIconSubPath("Arcanum_XtraArrowLeft"),
	getIconSubPath("Arcanum_XtraArrowRight"),
	getIconSubPath("Arcanum_XtraArrowUp"),
	getIconSubPath("Arcanum_XtraBooks"),
	getIconSubPath("Arcanum_XtraCastle"),
	getIconSubPath("Arcanum_XtraChest"),
	getIconSubPath("Arcanum_XtraCoffee"),
	getIconSubPath("Arcanum_XtraCompass"),
	getIconSubPath("Arcanum_XtraHelmet"),
	getIconSubPath("Arcanum_XtraPortal"),
	getIconSubPath("Arcanum_XtraSpeech"),
	getIconSubPath("sf_black_anomaly"),
	getIconSubPath("sf_black_armour"),
	getIconSubPath("sf_black_barrage"),
	getIconSubPath("sf_black_barrier"),
	getIconSubPath("sf_black_blade"),
	getIconSubPath("sf_black_book"),
	getIconSubPath("sf_black_burst"),
	getIconSubPath("sf_black_claw"),
	getIconSubPath("sf_black_clothes"),
	getIconSubPath("sf_black_core"),
	getIconSubPath("sf_black_crystal"),
	getIconSubPath("sf_black_dewdrop"),
	getIconSubPath("sf_black_dragonflight"),
	getIconSubPath("sf_black_dragonseye"),
	getIconSubPath("sf_black_eye"),
	getIconSubPath("sf_black_fist"),
	getIconSubPath("sf_black_flower"),
	getIconSubPath("sf_black_gem"),
	getIconSubPath("sf_black_head"),
	getIconSubPath("sf_black_hourglass"),
	getIconSubPath("sf_black_key"),
	getIconSubPath("sf_black_magic"),
	getIconSubPath("sf_black_map"),
	getIconSubPath("sf_black_miasma"),
	getIconSubPath("sf_black_necklace"),
	getIconSubPath("sf_black_needle"),
	getIconSubPath("sf_black_nexusoff"),
	getIconSubPath("sf_black_nexuson"),
	getIconSubPath("sf_black_orb"),
	getIconSubPath("sf_black_ore"),
	getIconSubPath("sf_black_pearl"),
	getIconSubPath("sf_black_petal"),
	getIconSubPath("sf_black_potion"),
	getIconSubPath("sf_black_power"),
	getIconSubPath("sf_black_questionmark"),
	getIconSubPath("sf_black_return"),
	getIconSubPath("sf_black_ring"),
	getIconSubPath("sf_black_scroll"),
	getIconSubPath("sf_black_shower"),
	getIconSubPath("sf_black_sigil"),
	getIconSubPath("sf_black_speed"),
	getIconSubPath("sf_black_sprint"),
	getIconSubPath("sf_black_starflower"),
	getIconSubPath("sf_black_sword"),
	getIconSubPath("sf_black_teleport"),
	getIconSubPath("sf_black_thread"),
	getIconSubPath("sf_black_time"),
	getIconSubPath("sf_black_tome"),
	getIconSubPath("sf_black_transform"),
	getIconSubPath("sf_blue_anomaly"),
	getIconSubPath("sf_blue_armour"),
	getIconSubPath("sf_blue_barrage"),
	getIconSubPath("sf_blue_barrier"),
	getIconSubPath("sf_blue_blade"),
	getIconSubPath("sf_blue_book"),
	getIconSubPath("sf_blue_burst"),
	getIconSubPath("sf_blue_claw"),
	getIconSubPath("sf_blue_clothes"),
	getIconSubPath("sf_blue_core"),
	getIconSubPath("sf_blue_crystal"),
	getIconSubPath("sf_blue_dewdrop"),
	getIconSubPath("sf_blue_dragonflight"),
	getIconSubPath("sf_blue_dragonseye"),
	getIconSubPath("sf_blue_eye"),
	getIconSubPath("sf_blue_fist"),
	getIconSubPath("sf_blue_flower"),
	getIconSubPath("sf_blue_gem"),
	getIconSubPath("sf_blue_head"),
	getIconSubPath("sf_blue_hourglass"),
	getIconSubPath("sf_blue_key"),
	getIconSubPath("sf_blue_magic"),
	getIconSubPath("sf_blue_map"),
	getIconSubPath("sf_blue_miasma"),
	getIconSubPath("sf_blue_necklace"),
	getIconSubPath("sf_blue_needle"),
	getIconSubPath("sf_blue_nexusoff"),
	getIconSubPath("sf_blue_nexuson"),
	getIconSubPath("sf_blue_orb"),
	getIconSubPath("sf_blue_ore"),
	getIconSubPath("sf_blue_pearl"),
	getIconSubPath("sf_blue_petal"),
	getIconSubPath("sf_blue_potion"),
	getIconSubPath("sf_blue_power"),
	getIconSubPath("sf_blue_questionmark"),
	getIconSubPath("sf_blue_return"),
	getIconSubPath("sf_blue_ring"),
	getIconSubPath("sf_blue_scroll"),
	getIconSubPath("sf_blue_shower"),
	getIconSubPath("sf_blue_sigil"),
	getIconSubPath("sf_blue_speed"),
	getIconSubPath("sf_blue_sprint"),
	getIconSubPath("sf_blue_starflower"),
	getIconSubPath("sf_blue_sword"),
	getIconSubPath("sf_blue_teleport"),
	getIconSubPath("sf_blue_thread"),
	getIconSubPath("sf_blue_time"),
	getIconSubPath("sf_blue_tome"),
	getIconSubPath("sf_blue_transform"),
	getIconSubPath("sf_bronze_anomaly"),
	getIconSubPath("sf_bronze_armour"),
	getIconSubPath("sf_bronze_barrage"),
	getIconSubPath("sf_bronze_barrier"),
	getIconSubPath("sf_bronze_blade"),
	getIconSubPath("sf_bronze_book"),
	getIconSubPath("sf_bronze_burst"),
	getIconSubPath("sf_bronze_claw"),
	getIconSubPath("sf_bronze_clothes"),
	getIconSubPath("sf_bronze_core"),
	getIconSubPath("sf_bronze_crystal"),
	getIconSubPath("sf_bronze_dewdrop"),
	getIconSubPath("sf_bronze_dragonflight"),
	getIconSubPath("sf_bronze_dragonseye"),
	getIconSubPath("sf_bronze_eye"),
	getIconSubPath("sf_bronze_fist"),
	getIconSubPath("sf_bronze_flower"),
	getIconSubPath("sf_bronze_gem"),
	getIconSubPath("sf_bronze_head"),
	getIconSubPath("sf_bronze_hourglass"),
	getIconSubPath("sf_bronze_key"),
	getIconSubPath("sf_bronze_magic"),
	getIconSubPath("sf_bronze_map"),
	getIconSubPath("sf_bronze_miasma"),
	getIconSubPath("sf_bronze_necklace"),
	getIconSubPath("sf_bronze_needle"),
	getIconSubPath("sf_bronze_nexusoff"),
	getIconSubPath("sf_bronze_nexuson"),
	getIconSubPath("sf_bronze_orb"),
	getIconSubPath("sf_bronze_ore"),
	getIconSubPath("sf_bronze_pearl"),
	getIconSubPath("sf_bronze_petal"),
	getIconSubPath("sf_bronze_potion"),
	getIconSubPath("sf_bronze_power"),
	getIconSubPath("sf_bronze_questionmark"),
	getIconSubPath("sf_bronze_return"),
	getIconSubPath("sf_bronze_ring"),
	getIconSubPath("sf_bronze_scroll"),
	getIconSubPath("sf_bronze_shower"),
	getIconSubPath("sf_bronze_sigil"),
	getIconSubPath("sf_bronze_speed"),
	getIconSubPath("sf_bronze_sprint"),
	getIconSubPath("sf_bronze_starflower"),
	getIconSubPath("sf_bronze_sword"),
	getIconSubPath("sf_bronze_teleport"),
	getIconSubPath("sf_bronze_thread"),
	getIconSubPath("sf_bronze_time"),
	getIconSubPath("sf_bronze_tome"),
	getIconSubPath("sf_bronze_transform"),
	getIconSubPath("sf_fire_anomaly"),
	getIconSubPath("sf_fire_armour"),
	getIconSubPath("sf_fire_barrage"),
	getIconSubPath("sf_fire_barrier"),
	getIconSubPath("sf_fire_blade"),
	getIconSubPath("sf_fire_book"),
	getIconSubPath("sf_fire_burst"),
	getIconSubPath("sf_fire_claw"),
	getIconSubPath("sf_fire_clothes"),
	getIconSubPath("sf_fire_core"),
	getIconSubPath("sf_fire_crystal"),
	getIconSubPath("sf_fire_dewdrop"),
	getIconSubPath("sf_fire_dragonflight"),
	getIconSubPath("sf_fire_dragonseye"),
	getIconSubPath("sf_fire_eye"),
	getIconSubPath("sf_fire_fist"),
	getIconSubPath("sf_fire_flower"),
	getIconSubPath("sf_fire_gem"),
	getIconSubPath("sf_fire_head"),
	getIconSubPath("sf_fire_hourglass"),
	getIconSubPath("sf_fire_key"),
	getIconSubPath("sf_fire_magic"),
	getIconSubPath("sf_fire_map"),
	getIconSubPath("sf_fire_miasma"),
	getIconSubPath("sf_fire_necklace"),
	getIconSubPath("sf_fire_needle"),
	getIconSubPath("sf_fire_nexusoff"),
	getIconSubPath("sf_fire_nexuson"),
	getIconSubPath("sf_fire_orb"),
	getIconSubPath("sf_fire_ore"),
	getIconSubPath("sf_fire_pearl"),
	getIconSubPath("sf_fire_petal"),
	getIconSubPath("sf_fire_potion"),
	getIconSubPath("sf_fire_power"),
	getIconSubPath("sf_fire_questionmark"),
	getIconSubPath("sf_fire_return"),
	getIconSubPath("sf_fire_ring"),
	getIconSubPath("sf_fire_scroll"),
	getIconSubPath("sf_fire_shower"),
	getIconSubPath("sf_fire_sigil"),
	getIconSubPath("sf_fire_speed"),
	getIconSubPath("sf_fire_sprint"),
	getIconSubPath("sf_fire_starflower"),
	getIconSubPath("sf_fire_sword"),
	getIconSubPath("sf_fire_teleport"),
	getIconSubPath("sf_fire_thread"),
	getIconSubPath("sf_fire_time"),
	getIconSubPath("sf_fire_tome"),
	getIconSubPath("sf_fire_transform"),
	getIconSubPath("sf_green_anomaly"),
	getIconSubPath("sf_green_armour"),
	getIconSubPath("sf_green_barrage"),
	getIconSubPath("sf_green_barrier"),
	getIconSubPath("sf_green_blade"),
	getIconSubPath("sf_green_book"),
	getIconSubPath("sf_green_burst"),
	getIconSubPath("sf_green_claw"),
	getIconSubPath("sf_green_clothes"),
	getIconSubPath("sf_green_core"),
	getIconSubPath("sf_green_crystal"),
	getIconSubPath("sf_green_dewdrop"),
	getIconSubPath("sf_green_dragonflight"),
	getIconSubPath("sf_green_dragonseye"),
	getIconSubPath("sf_green_eye"),
	getIconSubPath("sf_green_fist"),
	getIconSubPath("sf_green_flower"),
	getIconSubPath("sf_green_gem"),
	getIconSubPath("sf_green_head"),
	getIconSubPath("sf_green_hourglass"),
	getIconSubPath("sf_green_key"),
	getIconSubPath("sf_green_magic"),
	getIconSubPath("sf_green_map"),
	getIconSubPath("sf_green_miasma"),
	getIconSubPath("sf_green_necklace"),
	getIconSubPath("sf_green_needle"),
	getIconSubPath("sf_green_nexusoff"),
	getIconSubPath("sf_green_nexuson"),
	getIconSubPath("sf_green_orb"),
	getIconSubPath("sf_green_ore"),
	getIconSubPath("sf_green_pearl"),
	getIconSubPath("sf_green_petal"),
	getIconSubPath("sf_green_potion"),
	getIconSubPath("sf_green_power"),
	getIconSubPath("sf_green_questionmark"),
	getIconSubPath("sf_green_return"),
	getIconSubPath("sf_green_ring"),
	getIconSubPath("sf_green_scroll"),
	getIconSubPath("sf_green_shower"),
	getIconSubPath("sf_green_sigil"),
	getIconSubPath("sf_green_speed"),
	getIconSubPath("sf_green_sprint"),
	getIconSubPath("sf_green_starflower"),
	getIconSubPath("sf_green_sword"),
	getIconSubPath("sf_green_teleport"),
	getIconSubPath("sf_green_thread"),
	getIconSubPath("sf_green_time"),
	getIconSubPath("sf_green_tome"),
	getIconSubPath("sf_green_transform"),
	getIconSubPath("sf_inf_anomaly"),
	getIconSubPath("sf_inf_armour"),
	getIconSubPath("sf_inf_barrage"),
	getIconSubPath("sf_inf_barrier"),
	getIconSubPath("sf_inf_blade"),
	getIconSubPath("sf_inf_book"),
	getIconSubPath("sf_inf_burst"),
	getIconSubPath("sf_inf_claw"),
	getIconSubPath("sf_inf_clothes"),
	getIconSubPath("sf_inf_core"),
	getIconSubPath("sf_inf_crystal"),
	getIconSubPath("sf_inf_dewdrop"),
	getIconSubPath("sf_inf_dragonflight"),
	getIconSubPath("sf_inf_dragonseye"),
	getIconSubPath("sf_inf_eye"),
	getIconSubPath("sf_inf_fist"),
	getIconSubPath("sf_inf_flower"),
	getIconSubPath("sf_inf_gem"),
	getIconSubPath("sf_inf_head"),
	getIconSubPath("sf_inf_hourglass"),
	getIconSubPath("sf_inf_key"),
	getIconSubPath("sf_inf_magic"),
	getIconSubPath("sf_inf_map"),
	getIconSubPath("sf_inf_miasma"),
	getIconSubPath("sf_inf_necklace"),
	getIconSubPath("sf_inf_needle"),
	getIconSubPath("sf_inf_nexusoff"),
	getIconSubPath("sf_inf_nexuson"),
	getIconSubPath("sf_inf_orb"),
	getIconSubPath("sf_inf_ore"),
	getIconSubPath("sf_inf_pearl"),
	getIconSubPath("sf_inf_petal"),
	getIconSubPath("sf_inf_potion"),
	getIconSubPath("sf_inf_power"),
	getIconSubPath("sf_inf_questionmark"),
	getIconSubPath("sf_inf_return"),
	getIconSubPath("sf_inf_ring"),
	getIconSubPath("sf_inf_scroll"),
	getIconSubPath("sf_inf_shower"),
	getIconSubPath("sf_inf_sigil"),
	getIconSubPath("sf_inf_speed"),
	getIconSubPath("sf_inf_sprint"),
	getIconSubPath("sf_inf_starflower"),
	getIconSubPath("sf_inf_sword"),
	getIconSubPath("sf_inf_teleport"),
	getIconSubPath("sf_inf_thread"),
	getIconSubPath("sf_inf_time"),
	getIconSubPath("sf_inf_tome"),
	getIconSubPath("sf_inf_transform"),
	getIconSubPath("sf_red_anomaly"),
	getIconSubPath("sf_red_armour"),
	getIconSubPath("sf_red_barrage"),
	getIconSubPath("sf_red_barrier"),
	getIconSubPath("sf_red_blade"),
	getIconSubPath("sf_red_book"),
	getIconSubPath("sf_red_burst"),
	getIconSubPath("sf_red_claw"),
	getIconSubPath("sf_red_clothes"),
	getIconSubPath("sf_red_core"),
	getIconSubPath("sf_red_crystal"),
	getIconSubPath("sf_red_dewdrop"),
	getIconSubPath("sf_red_dragonflight"),
	getIconSubPath("sf_red_dragonseye"),
	getIconSubPath("sf_red_eye"),
	getIconSubPath("sf_red_fist"),
	getIconSubPath("sf_red_flower"),
	getIconSubPath("sf_red_gem"),
	getIconSubPath("sf_red_head"),
	getIconSubPath("sf_red_hourglass"),
	getIconSubPath("sf_red_key"),
	getIconSubPath("sf_red_magic"),
	getIconSubPath("sf_red_map"),
	getIconSubPath("sf_red_miasma"),
	getIconSubPath("sf_red_necklace"),
	getIconSubPath("sf_red_needle"),
	getIconSubPath("sf_red_nexusoff"),
	getIconSubPath("sf_red_nexuson"),
	getIconSubPath("sf_red_orb"),
	getIconSubPath("sf_red_ore"),
	getIconSubPath("sf_red_pearl"),
	getIconSubPath("sf_red_petal"),
	getIconSubPath("sf_red_potion"),
	getIconSubPath("sf_red_power"),
	getIconSubPath("sf_red_questionmark"),
	getIconSubPath("sf_red_return"),
	getIconSubPath("sf_red_ring"),
	getIconSubPath("sf_red_scroll"),
	getIconSubPath("sf_red_shower"),
	getIconSubPath("sf_red_sigil"),
	getIconSubPath("sf_red_speed"),
	getIconSubPath("sf_red_sprint"),
	getIconSubPath("sf_red_starflower"),
	getIconSubPath("sf_red_sword"),
	getIconSubPath("sf_red_teleport"),
	getIconSubPath("sf_red_thread"),
	getIconSubPath("sf_red_time"),
	getIconSubPath("sf_red_tome"),
	getIconSubPath("sf_red_transform"),

	-- Halloween - SF Matching
	getIconSubPath("halloween", "halloween_anomaly"),
	getIconSubPath("halloween", "halloween_armour"),
	getIconSubPath("halloween", "halloween_barrage"),
	getIconSubPath("halloween", "halloween_barrier"),
	getIconSubPath("halloween", "halloween_blade"),
	getIconSubPath("halloween", "halloween_book"),
	getIconSubPath("halloween", "halloween_burst"),
	getIconSubPath("halloween", "halloween_claw"),
	getIconSubPath("halloween", "halloween_clothes"),
	getIconSubPath("halloween", "halloween_core"),
	getIconSubPath("halloween", "halloween_crystal"),
	getIconSubPath("halloween", "halloween_dewdrop"),
	getIconSubPath("halloween", "halloween_dragonflight"),
	getIconSubPath("halloween", "halloween_dragonseye"),
	getIconSubPath("halloween", "halloween_eye"),
	getIconSubPath("halloween", "halloween_fist"),
	getIconSubPath("halloween", "halloween_flower"),
	getIconSubPath("halloween", "halloween_gem"),
	getIconSubPath("halloween", "halloween_head"),
	getIconSubPath("halloween", "halloween_hourglass"),
	getIconSubPath("halloween", "halloween_key"),
	getIconSubPath("halloween", "halloween_magic"),
	getIconSubPath("halloween", "halloween_map"),
	getIconSubPath("halloween", "halloween_miasma"),
	getIconSubPath("halloween", "halloween_necklace"),
	getIconSubPath("halloween", "halloween_needle"),
	getIconSubPath("halloween", "halloween_nexusoff"),
	getIconSubPath("halloween", "halloween_nexuson"),
	getIconSubPath("halloween", "halloween_orb"),
	getIconSubPath("halloween", "halloween_ore"),
	getIconSubPath("halloween", "halloween_pearl"),
	getIconSubPath("halloween", "halloween_petal"),
	getIconSubPath("halloween", "halloween_potion"),
	getIconSubPath("halloween", "halloween_power"),
	getIconSubPath("halloween", "halloween_questionmark"),
	getIconSubPath("halloween", "halloween_return"),
	getIconSubPath("halloween", "halloween_ring"),
	getIconSubPath("halloween", "halloween_scroll"),
	getIconSubPath("halloween", "halloween_shower"),
	getIconSubPath("halloween", "halloween_sigil"),
	getIconSubPath("halloween", "halloween_speed"),
	getIconSubPath("halloween", "halloween_sprint"),
	getIconSubPath("halloween", "halloween_starflower"),
	getIconSubPath("halloween", "halloween_sword"),
	getIconSubPath("halloween", "halloween_teleport"),
	getIconSubPath("halloween", "halloween_thread"),
	getIconSubPath("halloween", "halloween_time"),
	getIconSubPath("halloween", "halloween_tome"),
	getIconSubPath("halloween", "halloween_transform"),

	-- Halloween - Tricks & Treats!
	getIconSubPath("halloween", "halloween_spectral_boiledsweets"),
	getIconSubPath("halloween", "halloween_spectral_caramel"),
	getIconSubPath("halloween", "halloween_spectral_cupcake"),
	getIconSubPath("halloween", "halloween_spectral_pumpkin"),
	getIconSubPath("halloween", "halloween_spectral_spellbookopen"),

	getIconSubPath("halloween", "halloween_caramel"),
	getIconSubPath("halloween", "halloween_chocolatemuffin"),
	getIconSubPath("halloween", "halloween_crystalball"),
	getIconSubPath("halloween", "halloween_donutsprinkles"),
	getIconSubPath("halloween", "halloween_epsinomicon"),
	getIconSubPath("halloween", "halloween_gnashingteeth"),
	getIconSubPath("halloween", "halloween_hallowedcandle"),
	getIconSubPath("halloween", "halloween_hardcandy"),
	getIconSubPath("halloween", "halloween_lollypop"),
	getIconSubPath("halloween", "halloween_magicbeans"),
	getIconSubPath("halloween", "halloween_necromanticorb"),
	getIconSubPath("halloween", "halloween_poisonapple"),
	getIconSubPath("halloween", "halloween_pumpkin"),
	getIconSubPath("halloween", "halloween_risenghoul"),
	getIconSubPath("halloween", "halloween_shatteredmask"),
	getIconSubPath("halloween", "halloween_sheetghost"),
	getIconSubPath("halloween", "halloween_spider"),
	getIconSubPath("halloween", "halloween_spiderweb"),
	getIconSubPath("halloween", "halloween_swirlycandy"),
	getIconSubPath("halloween", "halloween_toffeeapple"),
	getIconSubPath("halloween", "halloween_tombstone"),
	getIconSubPath("halloween", "halloween_treatbag"),
	getIconSubPath("halloween", "halloween_vial"),

	-- Every Day Use Icons for Phase Interactions
	getIconSubPath("books", "book_blacksmith1"),
	getIconSubPath("books", "book_blacksmith2"),
	getIconSubPath("books", "book_bluedragon1"),
	getIconSubPath("books", "book_bluedragon2"),
	getIconSubPath("books", "book_deathknight1"),
	getIconSubPath("books", "book_deathknight2"),
	getIconSubPath("books", "book_draenei1"),
	getIconSubPath("books", "book_draenei2"),
	getIconSubPath("books", "book_firedruid1"),
	getIconSubPath("books", "book_greendragon1"),
	getIconSubPath("books", "book_greendragon2"),
	getIconSubPath("books", "book_kultiras1"),
	getIconSubPath("books", "book_legion1"),
	getIconSubPath("books", "book_legion2"),
	getIconSubPath("books", "book_legion3"),
	getIconSubPath("books", "book_nazjatar1"),
	getIconSubPath("books", "book_nazjatar2"),
	getIconSubPath("books", "book_nazjatar3"),
	getIconSubPath("books", "book_nazjatar4"),
	getIconSubPath("books", "book_necrolord1"),
	getIconSubPath("books", "book_necrolord2"),
	getIconSubPath("books", "book_necrolord3"),
	getIconSubPath("books", "book_necrolord4"),
	getIconSubPath("books", "book_nightborne1"),
	getIconSubPath("books", "book_nightborne2"),
	getIconSubPath("books", "book_nightelf1"),
	getIconSubPath("books", "book_nightelf2"),
	getIconSubPath("books", "book_nightelf3"),
	getIconSubPath("books", "book_nightelf4"),
	getIconSubPath("books", "book_nightelf5"),
	getIconSubPath("books", "book_nightelf6"),
	getIconSubPath("books", "book_nightfae1"),
	getIconSubPath("books", "book_nightfae2"),
	getIconSubPath("books", "book_orcclans1"),
	getIconSubPath("books", "book_orcclans2"),
	getIconSubPath("books", "book_orcclans3"),
	getIconSubPath("books", "book_orcclans4"),
	getIconSubPath("books", "book_paladin1"),
	getIconSubPath("books", "book_paladin2"),
	getIconSubPath("books", "book_panda1"),
	getIconSubPath("books", "book_panda2"),
	getIconSubPath("books", "book_priest1"),
	getIconSubPath("books", "book_sindorei1"),
	getIconSubPath("books", "book_sindorei2"),
	getIconSubPath("books", "book_sindorei3"),
	getIconSubPath("books", "book_uldaman1"),
	getIconSubPath("books", "book_uldaman2"),
	getIconSubPath("books", "book_venthyr1"),
	getIconSubPath("books", "book_venthyr2"),
	getIconSubPath("button", "button_bigred1"),
	getIconSubPath("button", "button_bigred2"),
	getIconSubPath("button", "button_switchblue"),
	getIconSubPath("button", "button_switchgreen"),
	getIconSubPath("button", "button_switchpink"),
	getIconSubPath("button", "button_switchyellow"),
	getIconSubPath("console", "console_broker"),
	getIconSubPath("console", "console_brokerorb"),
	getIconSubPath("console", "console_moonguard"),
	getIconSubPath("console", "console_nagaraid"),
	getIconSubPath("console", "console_nazmir"),
	getIconSubPath("console", "console_titan"),
	getIconSubPath("console", "console_titan1"),
	getIconSubPath("console", "console_titan2"),
	getIconSubPath("console", "console_workshop1"),
	getIconSubPath("console", "console_workshop2"),
	getIconSubPath("console", "console_workshop3"),
	getIconSubPath("console", "console_workshop4"),
	getIconSubPath("console", "console_zeppelin"),
	getIconSubPath("console", "console_zereth"),
	getIconSubPath("door", "door_broker"),
	getIconSubPath("door", "door_cosmicwing"),
	getIconSubPath("door", "door_dalaran_prison"),
	getIconSubPath("door", "door_dalaran_sewer"),
	getIconSubPath("door", "door_druidlarge"),
	getIconSubPath("door", "door_druidlarge_nightmare"),
	getIconSubPath("door", "door_forsaken"),
	getIconSubPath("door", "door_icecrown"),
	getIconSubPath("door", "door_karazhan"),
	getIconSubPath("door", "door_karazhanwall"),
	getIconSubPath("door", "door_kultiras_house"),
	getIconSubPath("door", "door_mechagnome"),
	getIconSubPath("door", "door_mogu"),
	getIconSubPath("door", "door_nathria1"),
	getIconSubPath("door", "door_nathria2"),
	getIconSubPath("door", "door_nazjatar"),
	getIconSubPath("door", "door_nazjatar1"),
	getIconSubPath("door", "door_nazjatar2"),
	getIconSubPath("door", "door_necrolord"),
	getIconSubPath("door", "door_pa_arch"),
	getIconSubPath("door", "door_pa_easttemple"),
	getIconSubPath("door", "door_pandaren_vault"),
	getIconSubPath("door", "door_prison01"),
	getIconSubPath("door", "door_progenitor"),
	getIconSubPath("door", "door_pvp_lordaeron"),
	getIconSubPath("door", "door_sumarraid"),
	getIconSubPath("door", "door_suramarcatacomb"),
	getIconSubPath("door", "door_torghast"),
	getIconSubPath("door", "door_uldir"),
	getIconSubPath("door", "door_ulduar"),
	getIconSubPath("door", "door_venthyr_crypt"),
	getIconSubPath("door", "door_venturecompany"),
	getIconSubPath("door", "door_vulpera"),
	getIconSubPath("door", "door_warden1"),
	getIconSubPath("door", "door_warden2"),
	getIconSubPath("door", "door_warden3"),
	getIconSubPath("door", "door_waycrest_double"),
	getIconSubPath("door", "door_waycrest_single"),
	getIconSubPath("door", "door_woe_palaces"),
	getIconSubPath("door", "door_worgen_cellar"),
	getIconSubPath("door", "door_worgen1"),
	getIconSubPath("door", "door_worgen2"),
	getIconSubPath("door", "door_zandalari"),
	getIconSubPath("door", "door_zerethmortis_"),
	getIconSubPath("lever", "lever_cityofgold"),
	getIconSubPath("lever", "lever_domination1"),
	getIconSubPath("lever", "lever_domination2"),
	getIconSubPath("lever", "lever_human1"),
	getIconSubPath("lever", "lever_human2"),
	getIconSubPath("lever", "lever_icecrown"),
	getIconSubPath("lever", "lever_mogu"),
	getIconSubPath("lever", "lever_ogre"),
	getIconSubPath("lever", "lever_orc"),
	getIconSubPath("lever", "lever_zuldrak"),
	getIconSubPath("locksandkeys", "key_broker"),
	getIconSubPath("locksandkeys", "key_domination"),
	getIconSubPath("locksandkeys", "key_generic1"),
	getIconSubPath("locksandkeys", "key_generic2"),
	getIconSubPath("locksandkeys", "key_generic3"),
	getIconSubPath("locksandkeys", "key_generic4"),
	getIconSubPath("locksandkeys", "key_legion"),
	getIconSubPath("locksandkeys", "key_plunder1"),
	getIconSubPath("locksandkeys", "key_plunder2"),
	getIconSubPath("locksandkeys", "key_plunder3"),
	getIconSubPath("locksandkeys", "key_plunder4"),
	getIconSubPath("locksandkeys", "key_roguelockpicking1"),
	getIconSubPath("locksandkeys", "key_roguelockpicking2"),
	getIconSubPath("locksandkeys", "key_roguelockpicking3"),
	getIconSubPath("locksandkeys", "key_roguelockpicking4"),
	getIconSubPath("locksandkeys", "key_roguelockpicking5"),
	getIconSubPath("locksandkeys", "lock_domination"),
	getIconSubPath("locksandkeys", "lock_generic1"),
	getIconSubPath("locksandkeys", "lock_rogue1"),
	getIconSubPath("locksandkeys", "lock_roguelockpicking1"),
	getIconSubPath("plaque", "plaque_broker2"),
	getIconSubPath("plaque", "plaque_broker3"),
	getIconSubPath("plaque", "plaque_broker4"),
	getIconSubPath("plaque", "plaque_broker5"),
	getIconSubPath("plaque", "plaque_broker6"),
	getIconSubPath("plaque", "plaque_broker7"),
	getIconSubPath("plaque", "plaque_broker8"),
	getIconSubPath("plaque", "plaque_dalaran"),
	getIconSubPath("plaque", "plaque_dwarven"),
	getIconSubPath("plaque", "plaque_generic_bronze1"),
	getIconSubPath("plaque", "plaque_generic_bronze2"),
	getIconSubPath("plaque", "plaque_generic_gold1"),
	getIconSubPath("plaque", "plaque_generic_gold2"),
	getIconSubPath("plaque", "plaque_generic_silver1"),
	getIconSubPath("plaque", "plaque_generic_silver2"),
	getIconSubPath("plaque", "plaque_generic_silver3"),
	getIconSubPath("plaque", "plaque_nightborn"),
	getIconSubPath("plaque", "plaque_rogue"),
	getIconSubPath("plaque", "plaque_vampire"),
	getIconSubPath("portals", "portal_arcanum_blue"),
	getIconSubPath("portals", "portal_arcanum_bronze"),
	getIconSubPath("portals", "portal_arcanum_earth"),
	getIconSubPath("portals", "portal_arcanum_emerald"),
	getIconSubPath("portals", "portal_arcanum_fire"),
	getIconSubPath("portals", "portal_arcanum_ice"),
	getIconSubPath("portals", "portal_arcanum_infinite"),
	getIconSubPath("portals", "portal_arcanum_lightning"),
	getIconSubPath("portals", "portal_arcanum_prismatic"),
	getIconSubPath("portals", "portal_arcanum_purple"),
	getIconSubPath("portals", "portal_arcanum_red"),
	getIconSubPath("portals", "portal_arcanum_tint"),
	getIconSubPath("portals", "portal_arcanum_void"),
	getIconSubPath("poster", "poster_darkmoon1"),
	getIconSubPath("poster", "poster_darkmoon2"),
	getIconSubPath("poster", "poster_forsaken_band"),
	getIconSubPath("poster", "poster_goblin_barber1"),
	getIconSubPath("poster", "poster_goblin_barber2"),
	getIconSubPath("poster", "poster_kultiras_prison"),
	getIconSubPath("poster", "poster_rogue_wanted1"),
	getIconSubPath("poster", "poster_rogue_wanted2"),
	getIconSubPath("poster", "poster_rogue_wanted3"),
	getIconSubPath("poster", "poster_rogue_wanted4"),
	getIconSubPath("poster", "poster_vampire"),
	getIconSubPath("signs", "sign_dalaran"),
	getIconSubPath("signs", "sign_dalaran_restaurant"),
	getIconSubPath("signs", "sign_nightborne"),
	getIconSubPath("signs", "sign_nightfae"),
	getIconSubPath("signs", "sign_oribos_bank"),
	getIconSubPath("signs", "sign_oribos_forge"),
	getIconSubPath("signs", "sign_oribos_scroll"),
	getIconSubPath("signs", "sign_oribos_tavern"),
	getIconSubPath("signs", "sign_oribos_trade"),
	getIconSubPath("signs", "sign_rogue_warning"),
	getIconSubPath("talktome", "talktome_exclaimblue"),
	getIconSubPath("talktome", "talktome_exclaimgreen"),
	getIconSubPath("talktome", "talktome_exclaimred"),
	getIconSubPath("talktome", "talktome_exclaimyellow"),
	getIconSubPath("talktome", "talktome_legendaryexclaimblue"),
	getIconSubPath("talktome", "talktome_legendaryexclaimgreen"),
	getIconSubPath("talktome", "talktome_legendaryexclaimred"),
	getIconSubPath("talktome", "talktome_legendaryexclaimyellow"),
	getIconSubPath("talktome", "talktome_petbattleblue"),
	getIconSubPath("talktome", "talktome_petbattlegreen"),
	getIconSubPath("talktome", "talktome_petbattlered"),
	getIconSubPath("talktome", "talktome_petbattleyellow"),
	getIconSubPath("talktome", "talktome_questionblue"),
	getIconSubPath("talktome", "talktome_questiongreen"),
	getIconSubPath("talktome", "talktome_questionred"),
	getIconSubPath("talktome", "talktome_questionyellow"),
	getIconSubPath("talktome", "talktome_trainerblue"),
	getIconSubPath("talktome", "talktome_trainergreen"),
	getIconSubPath("talktome", "talktome_trainerred"),
	getIconSubPath("talktome", "talktome_traineryellow"),
	getIconSubPath("vault", "vault_bloodelf"),
	getIconSubPath("vault", "vault_broker"),
	getIconSubPath("vault", "vault_dwarven"),
	getIconSubPath("vault", "vault_gnomish"),
	getIconSubPath("vault", "vault_great"),
	getIconSubPath("vault", "vault_human"),
	getIconSubPath("vault", "vault_kultiras"),
	getIconSubPath("vault", "vault_stormwind"),
	getIconSubPath("vault", "vault_ulduar"),

	-- what's next?

}

for i = 1, #SCFORGE_CUSTOM_ICONS do
	iconList[#iconList + 1] = SCFORGE_CUSTOM_ICONS[i]
end

local function getNumCustomIcons()
	return #SCFORGE_CUSTOM_ICONS
end

-- Handlers

local function convertPathToCustomIconIndex(path)
	return tIndexOf(SCFORGE_CUSTOM_ICONS, path)
end

local function getCustomIconPathFromIndex(index)
	return SCFORGE_CUSTOM_ICONS[tonumber(index)] or FALLBACK_ICON
end

local function getIconTextureFromName(name)
	local path
	if strfind(strlower(name), "addons/") then
		path = name
	else
		path = LibRPMedia:GetIconFileByName(name)
	end
	return path
end

local function SelectIcon(self, texID)
	if tonumber(texID) and tonumber(texID) < 10000 then
		texID = getCustomIconPathFromIndex(texID)
	end
	self.selectedTex = texID
	self:SetNormalTexture(texID)
end

local function ResetIcon(self)
	self.selectedTex = nil
	self:SetNormalTexture(FALLBACK_ICON)
end

local function getFinalIcon(icon)
	if icon then
		if tonumber(icon) and tonumber(icon) < 10000 then
			icon = getCustomIconPathFromIndex(icon)
			--dprint(nil, "Path of Custom Icon: " .. icon)
		else
			icon = icon
		end
	else
		--icon = "Interface/Icons/inv_misc_questionmark"
		--icon = Gems.gemPath("Violet")
		icon = FALLBACK_ICON
	end
	return icon
end

---@class UI_Icons
ns.UI.Icons = {
	FALLBACK_ICON = FALLBACK_ICON,
	iconList = iconList,
	SelectIcon = SelectIcon,
	ResetIcon = ResetIcon,
	getIconTextureFromName = getIconTextureFromName,
	convertPathToCustomIconIndex = convertPathToCustomIconIndex,
	getCustomIconPathFromIndex = getCustomIconPathFromIndex,
	getFinalIcon = getFinalIcon,
	getNumCustomIcons = getNumCustomIcons,
}
